name: InventoryBackup
version: 1.0
main: com.doksakura.InventoryBackup
api-version: 1.12
commands:
  restore:
    description: Restores a player's inventory from a backup.
    usage: /restore <player> [backup_index]
    permission: inventorybackup.restore
  listbackups:
    description: Lists available backups for a player.
    usage: /listbackups <player>
    permission: inventorybackup.list
permissions:
  inventorybackup.restore:
    description: Allows restoring a player's inventory.
    default: op
  inventorybackup.list:
    description: Allows listing a player's inventory backups.
    default: op
